from mlsgrid.pipeline.interface import Pipeline

pipeline = Pipeline(
    name="Property",
    resource="Property",
    transform=lambda rows: [
        {
            "id": row.get("@odata.id"),
            "HeatingYN": row.get("HeatingYN"),
            "WaterfrontYN": row.get("WaterfrontYN"),
            "TransactionBrokerCompensationType": row.get(
                "TransactionBrokerCompensationType"
            ),
            "BuildingAreaUnits": row.get("BuildingAreaUnits"),
            "StreetNumberNumeric": row.get("StreetNumberNumeric"),
            "ListAgentKeyNumeric": row.get("ListAgentKeyNumeric"),
            "BuildingAreaTotal": row.get("BuildingAreaTotal"),
            "CoveredSpaces": row.get("CoveredSpaces"),
            "ListOfficePhone": row.get("ListOfficePhone"),
            "ListingContractDate": row.get("ListingContractDate"),
            "OffMarketTimestamp": row.get("OffMarketTimestamp"),
            "PostalCode": row.get("PostalCode"),
            "ListAgentOfficePhone": row.get("ListAgentOfficePhone"),
            "ListAgentMobilePhone": row.get("ListAgentMobilePhone"),
            "ListPrice": row.get("ListPrice"),
            "WithdrawnDate": row.get("WithdrawnDate"),
            "DocumentsCount": row.get("DocumentsCount"),
            "Longitude": row.get("Longitude"),
            "ListOfficeMlsId": row.get("ListOfficeMlsId"),
            "OriginatingSystemModificationTimestamp": row.get(
                "OriginatingSystemModificationTimestamp"
            ),
            "InternetConsumerCommentYN": row.get("InternetConsumerCommentYN"),
            "DaysOnMarket": row.get("DaysOnMarket"),
            "PropertyType": row.get("PropertyType"),
            "Country": row.get("Country"),
            "MLSAreaMajor": row.get("MLSAreaMajor"),
            "OriginalEntryTimestamp": row.get("OriginalEntryTimestamp"),
            "ListAgentFullName": row.get("ListAgentFullName"),
            "SpecialListingConditions": [i for i in row["SpecialListingConditions"]]
            if row.get("SpecialListingConditions")
            else [],
            "ListingKey": row.get("ListingKey"),
            "SourceSystemKey": row.get("SourceSystemKey"),
            "LotSizeUnits": row.get("LotSizeUnits"),
            "PhotosCount": row.get("PhotosCount"),
            "OriginatingSystemKey": row.get("OriginatingSystemKey"),
            "ListingAgreement": row.get("ListingAgreement"),
            "ListAgentPreferredPhone": row.get("ListAgentPreferredPhone"),
            "MapCoordinate": row.get("MapCoordinate"),
            "PrivateRemarks": row.get("PrivateRemarks"),
            "ListOfficeKey": row.get("ListOfficeKey"),
            "StreetName": row.get("StreetName"),
            "CoolingYN": row.get("CoolingYN"),
            "MlsStatus": row.get("MlsStatus"),
            "OnMarketDate": row.get("OnMarketDate"),
            "City": row.get("City"),
            "SourceSystemName": row.get("SourceSystemName"),
            "ListAgentMiddleName": row.get("ListAgentMiddleName"),
            "PropertySubType": row.get("PropertySubType"),
            "ListOfficeEmail": row.get("ListOfficeEmail"),
            "MajorChangeTimestamp": row.get("MajorChangeTimestamp"),
            "StatusChangeTimestamp": row.get("StatusChangeTimestamp"),
            "PhotosChangeTimestamp": row.get("PhotosChangeTimestamp"),
            "ExpirationDate": row.get("ExpirationDate"),
            "StreetNumber": row.get("StreetNumber"),
            "ListingKeyNumeric": row.get("ListingKeyNumeric"),
            "ListAgentMlsId": row.get("ListAgentMlsId"),
            "UnparsedAddress": row.get("UnparsedAddress"),
            "ListingId": row.get("ListingId"),
            "ListAgentKey": row.get("ListAgentKey"),
            "BuildingAreaSource": row.get("BuildingAreaSource"),
            "ListAgentEmail": row.get("ListAgentEmail"),
            "OriginatingSystemID": row.get("OriginatingSystemID"),
            "ListOfficeKeyNumeric": row.get("ListOfficeKeyNumeric"),
            "InternetEntireListingDisplayYN": row.get("InternetEntireListingDisplayYN"),
            "InternetAutomatedValuationDisplayYN": row.get(
                "InternetAutomatedValuationDisplayYN"
            ),
            "OriginatingSystemName": row.get("OriginatingSystemName"),
            "CountyOrParish": row.get("CountyOrParish"),
            "SubAgencyCompensationType": row.get("SubAgencyCompensationType"),
            "TotalActualRent": row.get("TotalActualRent"),
            "ListAgentLastName": row.get("ListAgentLastName"),
            "ListOfficeFax": row.get("ListOfficeFax"),
            "Directions": row.get("Directions"),
            "Zoning": row.get("Zoning"),
            "ListAgentFirstName": row.get("ListAgentFirstName"),
            "BuyerAgencyCompensationType": row.get("BuyerAgencyCompensationType"),
            "InternetAddressDisplayYN": row.get("InternetAddressDisplayYN"),
            "Latitude": row.get("Latitude"),
            "StateOrProvince": row.get("StateOrProvince"),
            "MajorChangeType": row.get("MajorChangeType"),
            "ListOfficeName": row.get("ListOfficeName"),
            "SourceSystemID": row.get("SourceSystemID"),
            "OnMarketTimestamp": row.get("OnMarketTimestamp"),
            "OffMarketDate": row.get("OffMarketDate"),
            "StandardStatus": row.get("StandardStatus"),
            "ModificationTimestamp": row.get("ModificationTimestamp"),
            "MlgCanView": row.get("MlgCanView"),
        }
        for row in rows
    ],
    schema=[
        {"name": "id", "type": "STRING"},
        {"name": "HeatingYN", "type": "BOOLEAN"},
        {"name": "WaterfrontYN", "type": "BOOLEAN"},
        {"name": "TransactionBrokerCompensationType", "type": "STRING"},
        {"name": "BuildingAreaUnits", "type": "STRING"},
        {"name": "StreetNumberNumeric", "type": "NUMERIC"},
        {"name": "ListAgentKeyNumeric", "type": "NUMERIC"},
        {"name": "BuildingAreaTotal", "type": "NUMERIC"},
        {"name": "CoveredSpaces", "type": "NUMERIC"},
        {"name": "ListOfficePhone", "type": "STRING"},
        {"name": "ListingContractDate", "type": "STRING"},
        {"name": "OffMarketTimestamp", "type": "TIMESTAMP"},
        {"name": "PostalCode", "type": "STRING"},
        {"name": "ListAgentOfficePhone", "type": "STRING"},
        {"name": "ListAgentMobilePhone", "type": "STRING"},
        {"name": "ListPrice", "type": "NUMERIC"},
        {"name": "WithdrawnDate", "type": "STRING"},
        {"name": "DocumentsCount", "type": "NUMERIC"},
        {"name": "Longitude", "type": "NUMERIC"},
        {"name": "ListOfficeMlsId", "type": "STRING"},
        {"name": "OriginatingSystemModificationTimestamp", "type": "TIMESTAMP"},
        {"name": "InternetConsumerCommentYN", "type": "BOOLEAN"},
        {"name": "DaysOnMarket", "type": "NUMERIC"},
        {"name": "PropertyType", "type": "STRING"},
        {"name": "Country", "type": "STRING"},
        {"name": "MLSAreaMajor", "type": "STRING"},
        {"name": "OriginalEntryTimestamp", "type": "TIMESTAMP"},
        {"name": "ListAgentFullName", "type": "STRING"},
        {"name": "SpecialListingConditions", "type": "STRING", "mode": "REPEATED"},
        {"name": "ListingKey", "type": "STRING"},
        {"name": "SourceSystemKey", "type": "STRING"},
        {"name": "LotSizeUnits", "type": "STRING"},
        {"name": "PhotosCount", "type": "NUMERIC"},
        {"name": "OriginatingSystemKey", "type": "STRING"},
        {"name": "ListingAgreement", "type": "STRING"},
        {"name": "ListAgentPreferredPhone", "type": "STRING"},
        {"name": "MapCoordinate", "type": "STRING"},
        {"name": "PrivateRemarks", "type": "STRING"},
        {"name": "ListOfficeKey", "type": "STRING"},
        {"name": "StreetName", "type": "STRING"},
        {"name": "CoolingYN", "type": "BOOLEAN"},
        {"name": "MlsStatus", "type": "STRING"},
        {"name": "OnMarketDate", "type": "STRING"},
        {"name": "City", "type": "STRING"},
        {"name": "SourceSystemName", "type": "STRING"},
        {"name": "ListAgentMiddleName", "type": "STRING"},
        {"name": "PropertySubType", "type": "STRING"},
        {"name": "ListOfficeEmail", "type": "STRING"},
        {"name": "MajorChangeTimestamp", "type": "TIMESTAMP"},
        {"name": "StatusChangeTimestamp", "type": "TIMESTAMP"},
        {"name": "PhotosChangeTimestamp", "type": "TIMESTAMP"},
        {"name": "ExpirationDate", "type": "STRING"},
        {"name": "StreetNumber", "type": "STRING"},
        {"name": "ListingKeyNumeric", "type": "NUMERIC"},
        {"name": "ListAgentMlsId", "type": "STRING"},
        {"name": "UnparsedAddress", "type": "STRING"},
        {"name": "ListingId", "type": "STRING"},
        {"name": "ListAgentKey", "type": "STRING"},
        {"name": "BuildingAreaSource", "type": "STRING"},
        {"name": "ListAgentEmail", "type": "STRING"},
        {"name": "OriginatingSystemID", "type": "STRING"},
        {"name": "ListOfficeKeyNumeric", "type": "NUMERIC"},
        {"name": "InternetEntireListingDisplayYN", "type": "BOOLEAN"},
        {"name": "InternetAutomatedValuationDisplayYN", "type": "BOOLEAN"},
        {"name": "OriginatingSystemName", "type": "STRING"},
        {"name": "CountyOrParish", "type": "STRING"},
        {"name": "SubAgencyCompensationType", "type": "STRING"},
        {"name": "TotalActualRent", "type": "NUMERIC"},
        {"name": "ListAgentLastName", "type": "STRING"},
        {"name": "ListOfficeFax", "type": "STRING"},
        {"name": "Directions", "type": "STRING"},
        {"name": "Zoning", "type": "STRING"},
        {"name": "ListAgentFirstName", "type": "STRING"},
        {"name": "BuyerAgencyCompensationType", "type": "STRING"},
        {"name": "InternetAddressDisplayYN", "type": "BOOLEAN"},
        {"name": "Latitude", "type": "NUMERIC"},
        {"name": "StateOrProvince", "type": "STRING"},
        {"name": "MajorChangeType", "type": "STRING"},
        {"name": "ListOfficeName", "type": "STRING"},
        {"name": "SourceSystemID", "type": "STRING"},
        {"name": "OnMarketTimestamp", "type": "TIMESTAMP"},
        {"name": "OffMarketDate", "type": "STRING"},
        {"name": "StandardStatus", "type": "STRING"},
        {"name": "ModificationTimestamp", "type": "TIMESTAMP"},
        {"name": "MlgCanView", "type": "BOOLEAN"},
    ],
)
